# Data_Pipeline/configs/companies.yaml

companies:
  - ticker: AAPL
    name: Apple Inc.
    cik: "0000320193"
    
  - ticker: MSFT
    name: Microsoft Corporation
    cik: "0000789019"
    
  - ticker: GOOGL
    name: Alphabet Inc.
    cik: "0001652044"
    
  - ticker: AMZN
    name: Amazon.com Inc.
    cik: "0001018724"
    
  - ticker: TSLA
    name: Tesla Inc.
    cik: "0001318605"

  - ticker: NVDA
    name: NVIDIA Corporation
    cik: "0001045810"

  - ticker: META
    name: Meta Platforms, Inc.
    cik: "0001326801"

  - ticker: JPM
    name: JPMORGAN CHASE & CO.
    cik: "0000019617"

  - ticker: ORCL
    name: ORACLE CORP
    cik: "0001341439"

  - ticker: IBM
    name: INTERNATIONAL BUSINESS MACHINES CORP
    cik: "0000051143"

  - ticker: TM
    name: TOYOTA MOTOR CORP/
    cik: "0001094517"

  - ticker: C
    name: Citigroup Inc.
    cik: "0000831001"
